# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0e91360b859a7ee4407836e8e3acef6addcdc4743142f0837e53a878a128cc2c210c6d268a5252b1637c1ea405ea4fec7c91e5891208b4638b271a58da20ee2

test:
  secret_key_base: 654a3260d9fc20c282c83c5709a001a9c4dc01ab666c029be7de9c2677db1af88e5aa847f81b0cf905b4e96dbed379a4973ac779a697a7583cd558ab19275889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
